language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
services:
  - docker
env:
  - FORCE_NONINTERACTIVE=true
before_install:
  - docker pull google/cloud-sdk
  - docker run -d -p 8282:8282 google/cloud-sdk gcloud beta emulators datastore start --no-store-on-disk --project=test --host-port 0.0.0.0:8282
  - pip install -r requirements-test.txt
  - localstack start --docker &
install:
  - pip install .
  - pip install -r requirements.txt
# command to run tests
script: pytest